title: Hoshuuzora
email: azzamimutahharialfarrah@gmail.com
author: Azzami Mutahhari
description: >-
  Tempat pelarian dikala tomi gabut gak ada kerjaan
copyright: "Unpublished Work (cleft) 2022-{currentYear} {author}"
yat: 
  date_format: "%b %d, %Y"
defaults:
  home:
      heading: "Hoshuuzora"
      subheading: "Tempat pelarian dikala tomi gabut gak ada kerjaan"
      banner: "home.jpg"
favicon: "myIcon.ico"
night_mode: "on"
brand_color: "#389092"
header_pages:
  - index.html
  - categories.html
  - tags.html
  - archives.html
  - about.html
disqus:
  shortname: "hoshuuzora"
